# Generated by Django 4.1.1 on 2022-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='daysToArrivalTelega',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
