# Generated by Django 4.1.1 on 2022-09-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Main', '0002_city_daystoarrivaltelega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Waysted_days', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dealer',
            name='money',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='telega_weightkg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
