# Generated by Django 4.1.1 on 2022-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Main', '0004_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
