# Generated by Django 4.1.1 on 2022-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Main', '0005_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='amountKG',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
