# Generated by Django 4.1.1 on 2022-09-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Main', '0007_rename_telega_products_dealer_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amountKG',
            new_name='weightKG',
        ),
    ]
