# Generated by Django 4.1.1 on 2022-09-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Main', '0008_rename_amountkg_product_weightkg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weightKG',
            new_name='weightkg',
        ),
    ]
